#!/bin/bash

which sbt &> /dev/null

if [[ "$?" != 0 ]]; then
  echo "can't find sbt"
  exit 1
fi

if [[ "$1" == "jar" ]]; then

  sbt assembly || exit 1

  for f in $(ls -1 target | grep .jar); do
    tf=target/${f/.jar/}
    echo "#!/usr/bin/java -jar" > $tf
    cat target/$f >> $tf
    chmod +x $tf
    echo ">> build: $tf"
  done

else
  sbt $@
fi
